# Generated by Django 4.1.2 on 2022-10-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug name'),
        ),
    ]
